### ISSUE TITLE
Confluence Attachments: Error creating temp file in folder

### ISSUE THREAD

**Issue by Sylhare** [Sylhare/Atlassian#6]
When trying to load a file by any mean (drag and drop, or via uploading in the attachment section on the page) on any page in confluence from Firefox or Chrome, I get an error like this:

```groovy
java.lang.RuntimeException: Error creating temp file in folder: \\c\Program Files\Atlassian\Application Data\Confluence\attachments\ver003\193\104\10354693\26\113\9863526\32676452
    at com.atlassian.confluence.pages.persistence.dao.filesystem.FileSystemAttachmentDataUtil.createTempFile(FileSystemAttachmentDataUtil.java:66)

caused by: java.io.IOException: The user name or password is incorrect
    at java.io.WinNTFileSystem.createFileExclusively(Native Method) 
```

It seems like there are two errors, one is the impossibility to create a temporary file (lack of memory?) and the second seems to be an incorrect username password, which should not be true because I can do everything else and I am using the good log in. (Maybe a cookie problem?)

**Comment by Sylhare** [comment]
It was an _"out of memory"_ problem.
When going to  `Confluence Administration > System Information` you can check the **Java VM Memory Statistics**. Here you have an overview of the state of the memory used by the JVM to make Confluence work.

In my case I increased the Heap memory to 8Gb in order to solve the problem. (The number of user increased in the platform but not the memory, causing this gap).

Here is the link toward Atlassian full solution:
- [How to fix out of memory errors by increasing available memory](https://confluence.atlassian.com/confkb/how-to-fix-out-of-memory-errors-by-increasing-available-memory-154071.html)
